Conjunto de funcoes no open3d para utilizar no software do mestrado 

In [2]:
#Import the usefull libs
import open3d as o3d
import numpy as np
import copy

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [4]:
""" Atribuir valores a um objeto open3d - nuvem de pontos """
col1=np.asarray([-3,3,-3,3,-3,3,-3,3]) #Linha dos pontos em x
col2=np.asarray([3,3,-3,-3,3,3,-3,-3]) #Linha dos pontos em y
col3=np.asarray([0,0,0,0,6,6,6,6]) #Linha dos pontos em z

#Cria uma matriz de zeros (size(col1) linhas x 3 colunas) e preenche 
xyz = np.zeros((np.size(col1), 3)) 
xyz[:, 0] = np.reshape(col1, -1)
xyz[:, 1] = np.reshape(col2, -1)
xyz[:, 2] = np.reshape(col3, -1)

#Cria um objeto vazio de nuvem de pontos
pcd_demo = o3d.geometry.PointCloud()
#Transforma o array do numpy para um vetor 3d e transfere para points
pcd_demo.points = o3d.utility.Vector3dVector(xyz) 

print("xyz\n",xyz)
#Abre a janela de visualizacao para mostrar a figura
o3d.visualization.draw_geometries([pcd_demo])

#Escreve o "pcd_demo" com "print_pcd_demo.pcd" para futura leitura
o3d.io.write_point_cloud("print_pcd_demo.pcd",pcd_demo)

xyz
 [[-3.  3.  0.]
 [ 3.  3.  0.]
 [-3. -3.  0.]
 [ 3. -3.  0.]
 [-3.  3.  6.]
 [ 3.  3.  6.]
 [-3. -3.  6.]
 [ 3. -3.  6.]]


True

In [5]:
""" Atribuir valores a um objeto open3d - triangulos mesh """
N = 5
#Vertices e a propriedade com as coordenadas espaciais dos pontos que compoe o objeto triangle mesh
vertices = o3d.utility.Vector3dVector(
    np.array([[0, 0, 0], [1, 0, 0], [1, 0, 1], [0, 0, 1], [0.5, 0.5, 0.5]]))

#Indice dos 3 vertices que irao formar cada triangulo
triangles = o3d.utility.Vector3iVector(
    np.array([[0, 1, 2], [0, 2, 3], [0, 4, 1], [1, 4, 2], [2, 4, 3],
              [3, 4, 0]]))

#Cria o objeto TriangleMesh e preenche com vertices e triangulos 
mesh_np = o3d.geometry.TriangleMesh(vertices, triangles)

#Colorir o objeto
mesh_np.vertex_colors = o3d.utility.Vector3dVector(
    np.random.uniform(0, 1, size=(N, 3)))
mesh_np.compute_vertex_normals()
print(np.asarray(mesh_np.triangle_normals))
print("Displaying mesh made using numpy ...")

#Abre a janela de visualizacao para mostrar a figura
o3d.visualization.draw_geometries([mesh_np])

[[ 0.         -1.          0.        ]
 [ 0.         -1.          0.        ]
 [ 0.          0.70710678 -0.70710678]
 [ 0.70710678  0.70710678 -0.        ]
 [ 0.          0.70710678  0.70710678]
 [-0.70710678  0.70710678  0.        ]]
Displaying mesh made using numpy ...


In [5]:
""" Ler valores de um objeto open3d - nuvem de pontos """

ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

o3d.io.write_point_cloud("sync.pcd", pcd)
pcd_load = o3d.io.read_point_cloud("sync.pcd")
xyz_load = np.asarray(pcd_load.points)
print('xyz_load')
print(xyz_load)

o3d.visualization.draw_geometries([pcd_load])

xyz_load
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


In [6]:
""" Ler valores de um objeto open3d - triangulos mesh """

# Read a mesh and get its data as numpy arrays.
knot_mesh = o3d.data.KnotMesh()
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)
mesh.paint_uniform_color([0.5, 0.1, 0.3])
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Vertex Colors:')
print(np.asarray(mesh.vertex_colors))
print('Vertex Normals:')
print(np.asarray(mesh.vertex_normals))
print('Triangles:')
print(np.asarray(mesh.triangles))
print('Triangle Normals:')
print(np.asarray(mesh.triangle_normals))
print("Displaying mesh ...")
print(mesh)
o3d.visualization.draw([mesh])

Vertices:
[[  4.51268387  28.68865967 -76.55680847]
 [  7.63622284  35.52046967 -69.78063965]
 [  6.21986008  44.22465134 -64.82303619]
 ...
 [-22.12651634  31.28466606 -87.37570953]
 [-13.91188431  25.4865818  -86.25827026]
 [ -5.27768707  23.36245346 -81.43279266]]
Vertex Colors:
[[0.5 0.1 0.3]
 [0.5 0.1 0.3]
 [0.5 0.1 0.3]
 ...
 [0.5 0.1 0.3]
 [0.5 0.1 0.3]
 [0.5 0.1 0.3]]
Vertex Normals:
[]
Triangles:
[[   0   12   13]
 [   0   13    1]
 [   1   13   14]
 ...
 [1438   11 1439]
 [1439   11    0]
 [1439    0 1428]]
Triangle Normals:
[]
Displaying mesh ...
TriangleMesh with 1440 points and 2880 triangles.
[Open3D INFO] Window window_2 created.


KeyboardInterrupt: 